name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Initialize Git LFS (pull data for references)
      run: git lfs checkout

    - name: Setup .NET v5 (Target)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.300"

    - name: Setup .NET v6 (Host)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0"
        include-prerelease: True

    - name: Setup Stride fork packages access
      run: dotnet nuget add source --username ${{ secrets.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/manio143/index.json"
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release --no-build .\ProjectStepUp.Windows\ProjectStepUp.Windows.csproj
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: PublishedGame
        path: /Bin/Windows/Release/win-x64/publish/
